# Generated by Django 5.2.5 on 2025-09-09 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_customer_address_customer_date_joined_customer_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sku',
        ),
    ]
